/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NoAuthRouteImport } from './routes/_no-auth'
import { Route as AuthAdminRouteImport } from './routes/_auth/_admin'
import { Route as AuthManagerRouteImport } from './routes/_auth/_manager'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors/$authorId'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthProfilePrivacyRouteImport } from './routes/_auth/profile/privacy'
import { Route as AuthProfileSecurityRouteImport } from './routes/_auth/profile/security'
import { Route as AuthWriteIndexRouteImport } from './routes/_auth/write/index'
import { Route as AuthWritePostIdRouteImport } from './routes/_auth/write/$postId'
import { Route as NoAuthAboutIndexRouteImport } from './routes/_no-auth/about/index'
import { Route as NoAuthContactIndexRouteImport } from './routes/_no-auth/contact/index'
import { Route as NoAuthForgotPasswordIndexRouteImport } from './routes/_no-auth/forgot-password/index'
import { Route as NoAuthLoginIndexRouteImport } from './routes/_no-auth/login/index'
import { Route as NoAuthRegisterIndexRouteImport } from './routes/_no-auth/register/index'
import { Route as NoAuthResetPasswordIndexRouteImport } from './routes/_no-auth/reset-password/index'
import { Route as NoAuthTwoFactorAuthIndexRouteImport } from './routes/_no-auth/two-factor-auth/index'
import { Route as NoAuthVerifyEmailIndexRouteImport } from './routes/_no-auth/verify-email/index'
import { Route as AuthAdminSettingsIndexRouteImport } from './routes/_auth/_admin/settings/index'
import { Route as AuthManagerUsersIndexRouteImport } from './routes/_auth/_manager/users/index'
import { Route as AuthManagerUsersUserIdRouteImport } from './routes/_auth/_manager/users/$userId'
import { Route as AuthManagerUsersNewRouteImport } from './routes/_auth/_manager/users/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthRoute = NoAuthRouteImport.update({
  id: '/_no-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerRoute = AuthManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => AuthRoute,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilePrivacyRoute = AuthProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileSecurityRoute = AuthProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWriteIndexRoute = AuthWriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWritePostIdRoute = AuthWritePostIdRouteImport.update({
  id: '/write/$postId',
  path: '/write/$postId',
  getParentRoute: () => AuthRoute,
} as any)
const NoAuthAboutIndexRoute = NoAuthAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthContactIndexRoute = NoAuthContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthForgotPasswordIndexRoute =
  NoAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthLoginIndexRoute = NoAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthRegisterIndexRoute = NoAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthResetPasswordIndexRoute =
  NoAuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthTwoFactorAuthIndexRoute =
  NoAuthTwoFactorAuthIndexRouteImport.update({
    id: '/two-factor-auth/',
    path: '/two-factor-auth/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthVerifyEmailIndexRoute = NoAuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthAdminSettingsIndexRoute = AuthAdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthManagerUsersIndexRoute = AuthManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthManagerUsersUserIdRoute = AuthManagerUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthManagerUsersNewRoute = AuthManagerUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/terms/': typeof TermsIndexRoute
  '/profile/privacy': typeof AuthProfilePrivacyRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/write/$postId': typeof AuthWritePostIdRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/profile/': typeof AuthProfileIndexRoute
  '/write/': typeof AuthWriteIndexRoute
  '/about/': typeof NoAuthAboutIndexRoute
  '/contact/': typeof NoAuthContactIndexRoute
  '/forgot-password/': typeof NoAuthForgotPasswordIndexRoute
  '/login/': typeof NoAuthLoginIndexRoute
  '/register/': typeof NoAuthRegisterIndexRoute
  '/reset-password/': typeof NoAuthResetPasswordIndexRoute
  '/two-factor-auth/': typeof NoAuthTwoFactorAuthIndexRoute
  '/verify-email/': typeof NoAuthVerifyEmailIndexRoute
  '/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/users/new': typeof AuthManagerUsersNewRoute
  '/settings/': typeof AuthAdminSettingsIndexRoute
  '/users/': typeof AuthManagerUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/terms': typeof TermsIndexRoute
  '/profile/privacy': typeof AuthProfilePrivacyRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/write/$postId': typeof AuthWritePostIdRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/write': typeof AuthWriteIndexRoute
  '/about': typeof NoAuthAboutIndexRoute
  '/contact': typeof NoAuthContactIndexRoute
  '/forgot-password': typeof NoAuthForgotPasswordIndexRoute
  '/login': typeof NoAuthLoginIndexRoute
  '/register': typeof NoAuthRegisterIndexRoute
  '/reset-password': typeof NoAuthResetPasswordIndexRoute
  '/two-factor-auth': typeof NoAuthTwoFactorAuthIndexRoute
  '/verify-email': typeof NoAuthVerifyEmailIndexRoute
  '/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/users/new': typeof AuthManagerUsersNewRoute
  '/settings': typeof AuthAdminSettingsIndexRoute
  '/users': typeof AuthManagerUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_no-auth': typeof NoAuthRouteWithChildren
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/_manager': typeof AuthManagerRouteWithChildren
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/terms/': typeof TermsIndexRoute
  '/_auth/profile/privacy': typeof AuthProfilePrivacyRoute
  '/_auth/profile/security': typeof AuthProfileSecurityRoute
  '/_auth/write/$postId': typeof AuthWritePostIdRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/write/': typeof AuthWriteIndexRoute
  '/_no-auth/about/': typeof NoAuthAboutIndexRoute
  '/_no-auth/contact/': typeof NoAuthContactIndexRoute
  '/_no-auth/forgot-password/': typeof NoAuthForgotPasswordIndexRoute
  '/_no-auth/login/': typeof NoAuthLoginIndexRoute
  '/_no-auth/register/': typeof NoAuthRegisterIndexRoute
  '/_no-auth/reset-password/': typeof NoAuthResetPasswordIndexRoute
  '/_no-auth/two-factor-auth/': typeof NoAuthTwoFactorAuthIndexRoute
  '/_no-auth/verify-email/': typeof NoAuthVerifyEmailIndexRoute
  '/_auth/_manager/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/_auth/_manager/users/new': typeof AuthManagerUsersNewRoute
  '/_auth/_admin/settings/': typeof AuthAdminSettingsIndexRoute
  '/_auth/_manager/users/': typeof AuthManagerUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors/$authorId'
    | '/posts/$postId'
    | '/terms/'
    | '/profile/privacy'
    | '/profile/security'
    | '/write/$postId'
    | '/dashboard/'
    | '/profile/'
    | '/write/'
    | '/about/'
    | '/contact/'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/two-factor-auth/'
    | '/verify-email/'
    | '/users/$userId'
    | '/users/new'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors/$authorId'
    | '/posts/$postId'
    | '/terms'
    | '/profile/privacy'
    | '/profile/security'
    | '/write/$postId'
    | '/dashboard'
    | '/profile'
    | '/write'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor-auth'
    | '/verify-email'
    | '/users/$userId'
    | '/users/new'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_no-auth'
    | '/_auth/_admin'
    | '/_auth/_manager'
    | '/authors/$authorId'
    | '/posts/$postId'
    | '/terms/'
    | '/_auth/profile/privacy'
    | '/_auth/profile/security'
    | '/_auth/write/$postId'
    | '/_auth/dashboard/'
    | '/_auth/profile/'
    | '/_auth/write/'
    | '/_no-auth/about/'
    | '/_no-auth/contact/'
    | '/_no-auth/forgot-password/'
    | '/_no-auth/login/'
    | '/_no-auth/register/'
    | '/_no-auth/reset-password/'
    | '/_no-auth/two-factor-auth/'
    | '/_no-auth/verify-email/'
    | '/_auth/_manager/users/$userId'
    | '/_auth/_manager/users/new'
    | '/_auth/_admin/settings/'
    | '/_auth/_manager/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_no-auth': {
      id: '/_no-auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_manager': {
      id: '/_auth/_manager'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthManagerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/privacy': {
      id: '/_auth/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthProfilePrivacyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/security': {
      id: '/_auth/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthProfileSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/write/': {
      id: '/_auth/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof AuthWriteIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/write/$postId': {
      id: '/_auth/write/$postId'
      path: '/write/$postId'
      fullPath: '/write/$postId'
      preLoaderRoute: typeof AuthWritePostIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_no-auth/about/': {
      id: '/_no-auth/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof NoAuthAboutIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/contact/': {
      id: '/_no-auth/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof NoAuthContactIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/forgot-password/': {
      id: '/_no-auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof NoAuthForgotPasswordIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/login/': {
      id: '/_no-auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof NoAuthLoginIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/register/': {
      id: '/_no-auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof NoAuthRegisterIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/reset-password/': {
      id: '/_no-auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof NoAuthResetPasswordIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/two-factor-auth/': {
      id: '/_no-auth/two-factor-auth/'
      path: '/two-factor-auth'
      fullPath: '/two-factor-auth/'
      preLoaderRoute: typeof NoAuthTwoFactorAuthIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/verify-email/': {
      id: '/_no-auth/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof NoAuthVerifyEmailIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_auth/_admin/settings/': {
      id: '/_auth/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthAdminSettingsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_manager/users/': {
      id: '/_auth/_manager/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthManagerUsersIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/users/$userId': {
      id: '/_auth/_manager/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthManagerUsersUserIdRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/users/new': {
      id: '/_auth/_manager/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthManagerUsersNewRouteImport
      parentRoute: typeof AuthManagerRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminSettingsIndexRoute: typeof AuthAdminSettingsIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminSettingsIndexRoute: AuthAdminSettingsIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthManagerRouteChildren {
  AuthManagerUsersUserIdRoute: typeof AuthManagerUsersUserIdRoute
  AuthManagerUsersNewRoute: typeof AuthManagerUsersNewRoute
  AuthManagerUsersIndexRoute: typeof AuthManagerUsersIndexRoute
}

const AuthManagerRouteChildren: AuthManagerRouteChildren = {
  AuthManagerUsersUserIdRoute: AuthManagerUsersUserIdRoute,
  AuthManagerUsersNewRoute: AuthManagerUsersNewRoute,
  AuthManagerUsersIndexRoute: AuthManagerUsersIndexRoute,
}

const AuthManagerRouteWithChildren = AuthManagerRoute._addFileChildren(
  AuthManagerRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthManagerRoute: typeof AuthManagerRouteWithChildren
  AuthProfilePrivacyRoute: typeof AuthProfilePrivacyRoute
  AuthProfileSecurityRoute: typeof AuthProfileSecurityRoute
  AuthWritePostIdRoute: typeof AuthWritePostIdRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthWriteIndexRoute: typeof AuthWriteIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthManagerRoute: AuthManagerRouteWithChildren,
  AuthProfilePrivacyRoute: AuthProfilePrivacyRoute,
  AuthProfileSecurityRoute: AuthProfileSecurityRoute,
  AuthWritePostIdRoute: AuthWritePostIdRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthWriteIndexRoute: AuthWriteIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoAuthRouteChildren {
  NoAuthAboutIndexRoute: typeof NoAuthAboutIndexRoute
  NoAuthContactIndexRoute: typeof NoAuthContactIndexRoute
  NoAuthForgotPasswordIndexRoute: typeof NoAuthForgotPasswordIndexRoute
  NoAuthLoginIndexRoute: typeof NoAuthLoginIndexRoute
  NoAuthRegisterIndexRoute: typeof NoAuthRegisterIndexRoute
  NoAuthResetPasswordIndexRoute: typeof NoAuthResetPasswordIndexRoute
  NoAuthTwoFactorAuthIndexRoute: typeof NoAuthTwoFactorAuthIndexRoute
  NoAuthVerifyEmailIndexRoute: typeof NoAuthVerifyEmailIndexRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthAboutIndexRoute: NoAuthAboutIndexRoute,
  NoAuthContactIndexRoute: NoAuthContactIndexRoute,
  NoAuthForgotPasswordIndexRoute: NoAuthForgotPasswordIndexRoute,
  NoAuthLoginIndexRoute: NoAuthLoginIndexRoute,
  NoAuthRegisterIndexRoute: NoAuthRegisterIndexRoute,
  NoAuthResetPasswordIndexRoute: NoAuthResetPasswordIndexRoute,
  NoAuthTwoFactorAuthIndexRoute: NoAuthTwoFactorAuthIndexRoute,
  NoAuthVerifyEmailIndexRoute: NoAuthVerifyEmailIndexRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
