/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NoAuthRouteImport } from './routes/_no-auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthAdminRouteImport } from './routes/_auth/_admin'
import { Route as AuthManagerRouteImport } from './routes/_auth/_manager'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation/$orderId'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as AuthFavoritesIndexRouteImport } from './routes/_auth/favorites/index'
import { Route as AuthHomeIndexRouteImport } from './routes/_auth/home/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthOrdersOrderIdRouteImport } from './routes/_auth/orders/$orderId'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthProfilePrivacyRouteImport } from './routes/_auth/profile/privacy'
import { Route as AuthProfileSecurityRouteImport } from './routes/_auth/profile/security'
import { Route as NoAuthAboutIndexRouteImport } from './routes/_no-auth/about/index'
import { Route as NoAuthContactIndexRouteImport } from './routes/_no-auth/contact/index'
import { Route as NoAuthForgotPasswordIndexRouteImport } from './routes/_no-auth/forgot-password/index'
import { Route as NoAuthLoginIndexRouteImport } from './routes/_no-auth/login/index'
import { Route as NoAuthRegisterIndexRouteImport } from './routes/_no-auth/register/index'
import { Route as NoAuthResetPasswordIndexRouteImport } from './routes/_no-auth/reset-password/index'
import { Route as NoAuthTwoFactorAuthIndexRouteImport } from './routes/_no-auth/two-factor-auth/index'
import { Route as NoAuthVerifyEmailIndexRouteImport } from './routes/_no-auth/verify-email/index'
import { Route as AuthAdminImportIndexRouteImport } from './routes/_auth/_admin/import/index'
import { Route as AuthAdminSettingsIndexRouteImport } from './routes/_auth/_admin/settings/index'
import { Route as AuthManagerUsersIndexRouteImport } from './routes/_auth/_manager/users/index'
import { Route as AuthManagerUsersUserIdRouteImport } from './routes/_auth/_manager/users/$userId'
import { Route as AuthManagerUsersNewRouteImport } from './routes/_auth/_manager/users/new'
import { Route as AuthManagerAdminLibraryIndexRouteImport } from './routes/_auth/_manager/admin/library/index'
import { Route as AuthManagerAdminOrdersIndexRouteImport } from './routes/_auth/_manager/admin/orders/index'
import { Route as AuthManagerAdminProductsIndexRouteImport } from './routes/_auth/_manager/admin/products/index'
import { Route as AuthManagerAdminProductsProductIdRouteImport } from './routes/_auth/_manager/admin/products/$productId'
import { Route as AuthManagerAdminProductsNewRouteImport } from './routes/_auth/_manager/admin/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthRoute = NoAuthRouteImport.update({
  id: '/_no-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerRoute = AuthManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => AuthRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFavoritesIndexRoute = AuthFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeIndexRoute = AuthHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersOrderIdRoute = AuthOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilePrivacyRoute = AuthProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileSecurityRoute = AuthProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => AuthRoute,
} as any)
const NoAuthAboutIndexRoute = NoAuthAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthContactIndexRoute = NoAuthContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthForgotPasswordIndexRoute =
  NoAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthLoginIndexRoute = NoAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthRegisterIndexRoute = NoAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthResetPasswordIndexRoute =
  NoAuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthTwoFactorAuthIndexRoute =
  NoAuthTwoFactorAuthIndexRouteImport.update({
    id: '/two-factor-auth/',
    path: '/two-factor-auth/',
    getParentRoute: () => NoAuthRoute,
  } as any)
const NoAuthVerifyEmailIndexRoute = NoAuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthAdminImportIndexRoute = AuthAdminImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminSettingsIndexRoute = AuthAdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthManagerUsersIndexRoute = AuthManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthManagerUsersUserIdRoute = AuthManagerUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthManagerUsersNewRoute = AuthManagerUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthManagerAdminLibraryIndexRoute =
  AuthManagerAdminLibraryIndexRouteImport.update({
    id: '/admin/library/',
    path: '/admin/library/',
    getParentRoute: () => AuthManagerRoute,
  } as any)
const AuthManagerAdminOrdersIndexRoute =
  AuthManagerAdminOrdersIndexRouteImport.update({
    id: '/admin/orders/',
    path: '/admin/orders/',
    getParentRoute: () => AuthManagerRoute,
  } as any)
const AuthManagerAdminProductsIndexRoute =
  AuthManagerAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AuthManagerRoute,
  } as any)
const AuthManagerAdminProductsProductIdRoute =
  AuthManagerAdminProductsProductIdRouteImport.update({
    id: '/admin/products/$productId',
    path: '/admin/products/$productId',
    getParentRoute: () => AuthManagerRoute,
  } as any)
const AuthManagerAdminProductsNewRoute =
  AuthManagerAdminProductsNewRouteImport.update({
    id: '/admin/products/new',
    path: '/admin/products/new',
    getParentRoute: () => AuthManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/profile/privacy': typeof AuthProfilePrivacyRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/favorites/': typeof AuthFavoritesIndexRoute
  '/home/': typeof AuthHomeIndexRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/profile/': typeof AuthProfileIndexRoute
  '/about/': typeof NoAuthAboutIndexRoute
  '/contact/': typeof NoAuthContactIndexRoute
  '/forgot-password/': typeof NoAuthForgotPasswordIndexRoute
  '/login/': typeof NoAuthLoginIndexRoute
  '/register/': typeof NoAuthRegisterIndexRoute
  '/reset-password/': typeof NoAuthResetPasswordIndexRoute
  '/two-factor-auth/': typeof NoAuthTwoFactorAuthIndexRoute
  '/verify-email/': typeof NoAuthVerifyEmailIndexRoute
  '/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/users/new': typeof AuthManagerUsersNewRoute
  '/import/': typeof AuthAdminImportIndexRoute
  '/settings/': typeof AuthAdminSettingsIndexRoute
  '/users/': typeof AuthManagerUsersIndexRoute
  '/admin/products/$productId': typeof AuthManagerAdminProductsProductIdRoute
  '/admin/products/new': typeof AuthManagerAdminProductsNewRoute
  '/admin/library/': typeof AuthManagerAdminLibraryIndexRoute
  '/admin/orders/': typeof AuthManagerAdminOrdersIndexRoute
  '/admin/products/': typeof AuthManagerAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/terms': typeof TermsIndexRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/profile/privacy': typeof AuthProfilePrivacyRoute
  '/profile/security': typeof AuthProfileSecurityRoute
  '/favorites': typeof AuthFavoritesIndexRoute
  '/home': typeof AuthHomeIndexRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/about': typeof NoAuthAboutIndexRoute
  '/contact': typeof NoAuthContactIndexRoute
  '/forgot-password': typeof NoAuthForgotPasswordIndexRoute
  '/login': typeof NoAuthLoginIndexRoute
  '/register': typeof NoAuthRegisterIndexRoute
  '/reset-password': typeof NoAuthResetPasswordIndexRoute
  '/two-factor-auth': typeof NoAuthTwoFactorAuthIndexRoute
  '/verify-email': typeof NoAuthVerifyEmailIndexRoute
  '/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/users/new': typeof AuthManagerUsersNewRoute
  '/import': typeof AuthAdminImportIndexRoute
  '/settings': typeof AuthAdminSettingsIndexRoute
  '/users': typeof AuthManagerUsersIndexRoute
  '/admin/products/$productId': typeof AuthManagerAdminProductsProductIdRoute
  '/admin/products/new': typeof AuthManagerAdminProductsNewRoute
  '/admin/library': typeof AuthManagerAdminLibraryIndexRoute
  '/admin/orders': typeof AuthManagerAdminOrdersIndexRoute
  '/admin/products': typeof AuthManagerAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_no-auth': typeof NoAuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/_manager': typeof AuthManagerRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/_auth/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/_auth/profile/privacy': typeof AuthProfilePrivacyRoute
  '/_auth/profile/security': typeof AuthProfileSecurityRoute
  '/_auth/favorites/': typeof AuthFavoritesIndexRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_no-auth/about/': typeof NoAuthAboutIndexRoute
  '/_no-auth/contact/': typeof NoAuthContactIndexRoute
  '/_no-auth/forgot-password/': typeof NoAuthForgotPasswordIndexRoute
  '/_no-auth/login/': typeof NoAuthLoginIndexRoute
  '/_no-auth/register/': typeof NoAuthRegisterIndexRoute
  '/_no-auth/reset-password/': typeof NoAuthResetPasswordIndexRoute
  '/_no-auth/two-factor-auth/': typeof NoAuthTwoFactorAuthIndexRoute
  '/_no-auth/verify-email/': typeof NoAuthVerifyEmailIndexRoute
  '/_auth/_manager/users/$userId': typeof AuthManagerUsersUserIdRoute
  '/_auth/_manager/users/new': typeof AuthManagerUsersNewRoute
  '/_auth/_admin/import/': typeof AuthAdminImportIndexRoute
  '/_auth/_admin/settings/': typeof AuthAdminSettingsIndexRoute
  '/_auth/_manager/users/': typeof AuthManagerUsersIndexRoute
  '/_auth/_manager/admin/products/$productId': typeof AuthManagerAdminProductsProductIdRoute
  '/_auth/_manager/admin/products/new': typeof AuthManagerAdminProductsNewRoute
  '/_auth/_manager/admin/library/': typeof AuthManagerAdminLibraryIndexRoute
  '/_auth/_manager/admin/orders/': typeof AuthManagerAdminOrdersIndexRoute
  '/_auth/_manager/admin/products/': typeof AuthManagerAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order-confirmation/$orderId'
    | '/shop/$slug'
    | '/shop/'
    | '/terms/'
    | '/orders/$orderId'
    | '/profile/privacy'
    | '/profile/security'
    | '/favorites/'
    | '/home/'
    | '/orders/'
    | '/profile/'
    | '/about/'
    | '/contact/'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/two-factor-auth/'
    | '/verify-email/'
    | '/users/$userId'
    | '/users/new'
    | '/import/'
    | '/settings/'
    | '/users/'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/library/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order-confirmation/$orderId'
    | '/shop/$slug'
    | '/shop'
    | '/terms'
    | '/orders/$orderId'
    | '/profile/privacy'
    | '/profile/security'
    | '/favorites'
    | '/home'
    | '/orders'
    | '/profile'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor-auth'
    | '/verify-email'
    | '/users/$userId'
    | '/users/new'
    | '/import'
    | '/settings'
    | '/users'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/library'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_no-auth'
    | '/cart'
    | '/checkout'
    | '/_auth/_admin'
    | '/_auth/_manager'
    | '/order-confirmation/$orderId'
    | '/shop/$slug'
    | '/shop/'
    | '/terms/'
    | '/_auth/orders/$orderId'
    | '/_auth/profile/privacy'
    | '/_auth/profile/security'
    | '/_auth/favorites/'
    | '/_auth/home/'
    | '/_auth/orders/'
    | '/_auth/profile/'
    | '/_no-auth/about/'
    | '/_no-auth/contact/'
    | '/_no-auth/forgot-password/'
    | '/_no-auth/login/'
    | '/_no-auth/register/'
    | '/_no-auth/reset-password/'
    | '/_no-auth/two-factor-auth/'
    | '/_no-auth/verify-email/'
    | '/_auth/_manager/users/$userId'
    | '/_auth/_manager/users/new'
    | '/_auth/_admin/import/'
    | '/_auth/_admin/settings/'
    | '/_auth/_manager/users/'
    | '/_auth/_manager/admin/products/$productId'
    | '/_auth/_manager/admin/products/new'
    | '/_auth/_manager/admin/library/'
    | '/_auth/_manager/admin/orders/'
    | '/_auth/_manager/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_no-auth': {
      id: '/_no-auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_manager': {
      id: '/_auth/_manager'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthManagerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/favorites/': {
      id: '/_auth/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof AuthFavoritesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthHomeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/$orderId': {
      id: '/_auth/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthOrdersOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/privacy': {
      id: '/_auth/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthProfilePrivacyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/security': {
      id: '/_auth/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthProfileSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_no-auth/about/': {
      id: '/_no-auth/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof NoAuthAboutIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/contact/': {
      id: '/_no-auth/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof NoAuthContactIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/forgot-password/': {
      id: '/_no-auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof NoAuthForgotPasswordIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/login/': {
      id: '/_no-auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof NoAuthLoginIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/register/': {
      id: '/_no-auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof NoAuthRegisterIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/reset-password/': {
      id: '/_no-auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof NoAuthResetPasswordIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/two-factor-auth/': {
      id: '/_no-auth/two-factor-auth/'
      path: '/two-factor-auth'
      fullPath: '/two-factor-auth/'
      preLoaderRoute: typeof NoAuthTwoFactorAuthIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/verify-email/': {
      id: '/_no-auth/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof NoAuthVerifyEmailIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_auth/_admin/import/': {
      id: '/_auth/_admin/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthAdminImportIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_admin/settings/': {
      id: '/_auth/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthAdminSettingsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_manager/users/': {
      id: '/_auth/_manager/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthManagerUsersIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/users/$userId': {
      id: '/_auth/_manager/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthManagerUsersUserIdRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/users/new': {
      id: '/_auth/_manager/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthManagerUsersNewRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/admin/library/': {
      id: '/_auth/_manager/admin/library/'
      path: '/admin/library'
      fullPath: '/admin/library/'
      preLoaderRoute: typeof AuthManagerAdminLibraryIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/admin/orders/': {
      id: '/_auth/_manager/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthManagerAdminOrdersIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/admin/products/': {
      id: '/_auth/_manager/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthManagerAdminProductsIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/admin/products/$productId': {
      id: '/_auth/_manager/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AuthManagerAdminProductsProductIdRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/_manager/admin/products/new': {
      id: '/_auth/_manager/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthManagerAdminProductsNewRouteImport
      parentRoute: typeof AuthManagerRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminImportIndexRoute: typeof AuthAdminImportIndexRoute
  AuthAdminSettingsIndexRoute: typeof AuthAdminSettingsIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminImportIndexRoute: AuthAdminImportIndexRoute,
  AuthAdminSettingsIndexRoute: AuthAdminSettingsIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthManagerRouteChildren {
  AuthManagerUsersUserIdRoute: typeof AuthManagerUsersUserIdRoute
  AuthManagerUsersNewRoute: typeof AuthManagerUsersNewRoute
  AuthManagerUsersIndexRoute: typeof AuthManagerUsersIndexRoute
  AuthManagerAdminProductsProductIdRoute: typeof AuthManagerAdminProductsProductIdRoute
  AuthManagerAdminProductsNewRoute: typeof AuthManagerAdminProductsNewRoute
  AuthManagerAdminLibraryIndexRoute: typeof AuthManagerAdminLibraryIndexRoute
  AuthManagerAdminOrdersIndexRoute: typeof AuthManagerAdminOrdersIndexRoute
  AuthManagerAdminProductsIndexRoute: typeof AuthManagerAdminProductsIndexRoute
}

const AuthManagerRouteChildren: AuthManagerRouteChildren = {
  AuthManagerUsersUserIdRoute: AuthManagerUsersUserIdRoute,
  AuthManagerUsersNewRoute: AuthManagerUsersNewRoute,
  AuthManagerUsersIndexRoute: AuthManagerUsersIndexRoute,
  AuthManagerAdminProductsProductIdRoute:
    AuthManagerAdminProductsProductIdRoute,
  AuthManagerAdminProductsNewRoute: AuthManagerAdminProductsNewRoute,
  AuthManagerAdminLibraryIndexRoute: AuthManagerAdminLibraryIndexRoute,
  AuthManagerAdminOrdersIndexRoute: AuthManagerAdminOrdersIndexRoute,
  AuthManagerAdminProductsIndexRoute: AuthManagerAdminProductsIndexRoute,
}

const AuthManagerRouteWithChildren = AuthManagerRoute._addFileChildren(
  AuthManagerRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthManagerRoute: typeof AuthManagerRouteWithChildren
  AuthOrdersOrderIdRoute: typeof AuthOrdersOrderIdRoute
  AuthProfilePrivacyRoute: typeof AuthProfilePrivacyRoute
  AuthProfileSecurityRoute: typeof AuthProfileSecurityRoute
  AuthFavoritesIndexRoute: typeof AuthFavoritesIndexRoute
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthManagerRoute: AuthManagerRouteWithChildren,
  AuthOrdersOrderIdRoute: AuthOrdersOrderIdRoute,
  AuthProfilePrivacyRoute: AuthProfilePrivacyRoute,
  AuthProfileSecurityRoute: AuthProfileSecurityRoute,
  AuthFavoritesIndexRoute: AuthFavoritesIndexRoute,
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoAuthRouteChildren {
  NoAuthAboutIndexRoute: typeof NoAuthAboutIndexRoute
  NoAuthContactIndexRoute: typeof NoAuthContactIndexRoute
  NoAuthForgotPasswordIndexRoute: typeof NoAuthForgotPasswordIndexRoute
  NoAuthLoginIndexRoute: typeof NoAuthLoginIndexRoute
  NoAuthRegisterIndexRoute: typeof NoAuthRegisterIndexRoute
  NoAuthResetPasswordIndexRoute: typeof NoAuthResetPasswordIndexRoute
  NoAuthTwoFactorAuthIndexRoute: typeof NoAuthTwoFactorAuthIndexRoute
  NoAuthVerifyEmailIndexRoute: typeof NoAuthVerifyEmailIndexRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthAboutIndexRoute: NoAuthAboutIndexRoute,
  NoAuthContactIndexRoute: NoAuthContactIndexRoute,
  NoAuthForgotPasswordIndexRoute: NoAuthForgotPasswordIndexRoute,
  NoAuthLoginIndexRoute: NoAuthLoginIndexRoute,
  NoAuthRegisterIndexRoute: NoAuthRegisterIndexRoute,
  NoAuthResetPasswordIndexRoute: NoAuthResetPasswordIndexRoute,
  NoAuthTwoFactorAuthIndexRoute: NoAuthTwoFactorAuthIndexRoute,
  NoAuthVerifyEmailIndexRoute: NoAuthVerifyEmailIndexRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
